site:
  domain: "http://myksc.cn"
  env: "dev"

db:
  drivername: "mysql"
  hostname: "127.0.0.1"
  port: "3306"
  dbuser: "ksc"
  dbpwd: "ksc"
  dbname: "ksc"
  charset: "utf8"
  lifetime: 5
  maxconn: 500
  idleconn: 100
